### ISSUE TITLE
Summary - Exceeds Expectations

### ISSUE THREAD

**Issue by tbergen1** [tashk85/prj-rev-bwfs-dasmoto#4]
Overall, you did really great with this project.  Your formatting for your HTML/CSS is done really well.  You also chose great names for your CSS selector IDs and you chose your proper HTML elements based on their semantic meaning, which shows good insight.  The only thing you could improve upon would be to add comments in your files to provide a bit more context.  Other than that, great job here.  Keep up the good work!

**Comment by tashk85** [comment]
Thank you, will keep the comments in mind going forward!
